version: "2"

linters:
  enable:
    - govet       # suspicious constructs
    - staticcheck # broad static analysis
    - errcheck    # unchecked errors
    - unused      # unused code
    - misspell    # typos in comments/strings

formatters:
  enable:
    - gofmt     # formatting
    - goimports # import ordering

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
